baseURL = 'https://cptsai.github.io/'
languageCode = 'en-us'
title = 'CP Tsai Blog'
theme = "PaperMod"

[params]
    env = "production"
    title = "CP Tsai Blog"
    description = "Research, Food, Coffee, Exercise & Life"
    author = "CP Tsai"
    math = true
    ShowToc = true

    [params.homeInfoParams]
        Title = "Hi there ðŸ‘‹"
        Content = "I'm CP Tsai."

# ---Menu Configuration---
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 10

[[menu.main]]
    name = "All Posts"
    url = "/posts/"
    weight = 20

[[menu.main]]
    name = "Archive"
    url = "/archives/"
    weight = 30

[[menu.main]]
    name = "Project"
    url = "/projects/"
    weight = 40

[[menu.main]]
    name = "Publication"
    url = "/publications/"
    weight = 50

[outputs]
    home = ["HTML", "RSS", "JSON"]