baseURL = 'https://cptsai.github.io/'
languageCode = 'en-us'
title = 'CP Tsai Blog'
theme = "PaperMod"

[params]
    env = "production"
    title = "CP Tsai Blog"
    description = " Research, Food, Coffee, Exercise & Life"
    author = "CP Tsai"
    math = true

    # é¡¯ç¤ºã€Œé¦–é å¤§åœ–æ¨¡å¼ã€
    [params.homeInfoParams]
        Title = "Hi there ğŸ‘‹"
        Content = "æ­¡è¿ä¾†åˆ°æˆ‘çš„ç ”ç©¶èˆ‡ç”Ÿæ´»éš¨ç­†ã€‚"

    # è¨­å®šç¤¾äº¤é€£çµ
    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/cptsai"